# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='会议室名称')),
                ('capacity', models.IntegerField(verbose_name='容量')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='预定时间')),
                ('booking_time', models.IntegerField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (6, '12:00'), (7, '13:00'), (8, '14:00'), (9, '15:00'), (10, '16:00'), (11, '17:00')], verbose_name='预定时间段')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Room', verbose_name='预定会议室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预定人')),
            ],
        ),
    ]
